apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-react-framework
spec:
  replicas: 3

  template:
    spec:
      containers:
        - name: app
          image: mini-react-framework:latest